import * as esbuild from "esbuild";
import { readFile } from "node:fs/promises";
import { spawn } from "node:child_process";

const watch = process.argv.includes("--watch");
const outfile =
  "custom_components/imprint_refinery/www/imprint-refinery-card.js";

const run = (command, args) =>
  new Promise((resolve, reject) => {
    const child = spawn(command, args, {
      stdio: ["ignore", "ignore", "ignore"],
    });
    child.once("error", reject);
    child.once("exit", (code) =>
      code === 0
        ? resolve()
        : reject(new Error(`${command} exited with status ${code}`)),
    );
  });

const safeDeployConfig = async () => {
  let file = {};
  const configPath =
    process.env.IMPRINT_REFINERY_DEPLOY_CONFIG ||
    process.env.IMPRINT_REFINERY_DEPLOY_CONFIG_PATH;
  if (configPath) file = JSON.parse(await readFile(configPath, "utf8"));
  const target =
    process.env.IMPRINT_REFINERY_DEPLOY_TARGET || file.target || "";
  const destination =
    process.env.IMPRINT_REFINERY_DEPLOY_PATH ||
    file.path ||
    file.destination ||
    "";
  if (!target && !destination) return null;
  if (!target || !destination)
    throw new Error(
      "Imprint Refinery deployment needs both a target and destination path",
    );
  if (!/^[A-Za-z0-9_.@:-]+$/.test(target))
    throw new Error(
      "Imprint Refinery deployment target contains unsafe characters",
    );
  if (
    !/^\/[A-Za-z0-9._/-]+$/.test(destination) ||
    destination.split("/").includes("..") ||
    destination.endsWith("/")
  )
    throw new Error(
      "Imprint Refinery deployment path is not a safe absolute file path",
    );
  return { target, destination };
};

class DeployQueue {
  running = false;
  pending = false;
  waiters = [];
  configPromise = safeDeployConfig();

  enqueue() {
    this.pending = true;
    const completed = new Promise((resolve, reject) =>
      this.waiters.push({ resolve, reject }),
    );
    void this.pump();
    return completed;
  }

  async pump() {
    if (this.running) return;
    this.running = true;
    try {
      const config = await this.configPromise;
      while (this.pending) {
        this.pending = false;
        const batch = this.waiters.splice(0);
        try {
          if (config) {
            console.log("Deploying Imprint Refinery frontend…");
            const staged = `${config.destination}.stage-${process.pid}`;
            await run("scp", [outfile, `${config.target}:${staged}`]);
            await run("ssh", [
              config.target,
              "mv",
              "--",
              staged,
              config.destination,
            ]);
            console.log("Imprint Refinery frontend deployed atomically.");
          }
          batch.forEach((waiter) => waiter.resolve());
        } catch (error) {
          batch.forEach((waiter) => waiter.reject(error));
        }
      }
    } catch (error) {
      this.waiters.splice(0).forEach((waiter) => waiter.reject(error));
      this.pending = false;
    } finally {
      this.running = false;
      if (this.pending) void this.pump();
    }
  }
}

const deploys = new DeployQueue();
const deployPlugin = {
  name: "optional-serialized-deploy",
  setup(build) {
    build.onEnd(async (result) => {
      if (result.errors.length) return;
      console.log("Build complete.");
      try {
        await deploys.enqueue();
      } catch {
        if (!watch)
          throw new Error("Imprint Refinery frontend deployment failed");
        console.error(
          "Imprint Refinery frontend deployment failed; the watcher will retry after the next successful build.",
        );
      }
    });
  },
};

const options = {
  entryPoints: ["frontend/imprint-refinery-card.ts"],
  bundle: true,
  format: "esm",
  target: "es2022",
  sourcemap: false,
  minify: false,
  minifyWhitespace: true,
  legalComments: "eof",
  outfile,
  banner: {
    js: "/* Imprint Refinery v0.3.0 — generated by esbuild; edit frontend/, not this file. */",
  },
  plugins: [deployPlugin],
};

if (watch) {
  const context = await esbuild.context(options);
  await context.watch();
  console.log("Watching Imprint Refinery frontend sources…");
} else {
  await esbuild.build(options);
}
